### ISSUE TITLE
About the computer configuration

### ISSUE THREAD

**Issue by StacyIssac** [GestureGeneration/Speech_driven_gesture_generation_with_autoencoder#10]
Hello, I would like to ask you about the computer configuration used in your trainning model and the approximate trainning time. :)

**Comment by Svito-zar** [comment]
Hi @StacyIssac .
The model was trained on a computer with 1 GPU, namely NVIDIA TITAN Xp.
A training epoch took 20 sec or so.
20 sec x 500 epochs is about 150 min
Did I answer your question?
Best,
Taras
