### ISSUE TITLE
how to run this two parts

### ISSUE THREAD

**Issue by guofengming11** [GestureGeneration/Speech_driven_gesture_generation_with_autoencoder#12]
![image](https://user-images.githubusercontent.com/67827587/116034411-d2afb300-a695-11eb-9daa-1dd455a88b4c.png)
Someone can give  useage examples（command） of this two parts？
Thanks ！！

**Comment by Svito-zar** [comment]
Dear @guofengming11-chinese ,
This script shows usage example:
https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/blob/master/example_scripts/proposed_test.sh

**Comment by Svito-zar** [comment]
@guofengming11-chinese , has this question been answered?

**Comment by guofengming11** [comment]
yes，thanks
