### ISSUE TITLE
How do you do the alignment between audio features and posture frames?

### ISSUE THREAD

**Issue by wubowen416** [GestureGeneration/Speech_driven_gesture_generation_with_autoencoder#3]
This is an excellent work. As a student working on gesture generation, I am very appreciate of this code. Thank you.

However I've got a question for you guys.

I notice that in the file **create_vector.py**, specifically in **create_vectors function**, there is a **step 3**, which is commented as "align vector length". It is written as,

```python:
# Step 3: Align vector length
input_vectors, output_vectors = shorten(input_vectors, output_vectors)
```
and,

```python:
def shorten(arr1, arr2):
    min_len = min(len(arr1), len(arr2))

    arr1 = arr1[:min_len]
    arr2 = arr2[:min_len]

    return arr1, arr2
```

In my view it was supposed to be doing some kind of alignment, because in your work, all MFCC features were concatenated as one vector during training. Therefore it is crucial to know which part of MFCC features is corresponding to posture frames.

The problem is that **if the vectors were simply cut by shorter length of MFCCs and posture frames, aren't some information lost?** For example, if the length of MFCCs is longer than posture frames, the part in posture frames exceeding the length of MFCCs will be deleted. 

Looking forward to your reply!

**Comment by Svito-zar** [comment]
Thank you for your question!

You are right. But the difference between those vector lengths is negligible (it comes from the sliding window in MFCC processing). You can print it out and convince yourself that it is just a few frames difference.

Apart from that, we are taking 1.5s of the past and 1.5s of the future for each sliding window, so even if there is a slight misalignment (1 frame out of 60) - all the relevant information will still be taken into account.

Does this answer your question?

**Comment by wubowen416** [comment]
Thank you for your reply!

Do you mean the alignment are done by sliding the window in MFCC processing at certain stride and window size? I see, thank you!

I also have another question.

Have you guys tried to train on one audio file at a time corresponding to one series of motion frames? I think the reason that in your work all audio are concatenated is that the conversation is continuous. What do you think of the performance of training the model on only one series of audio at one time.

**Comment by Svito-zar** [comment]
Yes, you are right again: every sequence we obtain using a sliding window belongs to single audio. But the dataset contains sequences from many different audio files and they are being shuffled every epoch. So every batch during training contains sequences from different audios.

**Comment by Svito-zar** [comment]
If you have questions on different aspects of the model - please, pose them in a separate issue

**Comment by Svito-zar** [comment]
@wubowen416 , did I answer your question fully?

**Comment by wubowen416** [comment]
I understand! Thank you very much!
