### ISSUE TITLE
How do you divide the each long sample to short samples?

### ISSUE THREAD

**Issue by chuangyu-robotics** [GestureGeneration/Speech_driven_gesture_generation_with_autoencoder#8]
I looked over your code. thank you very much for sharing the great work at first.

I know In genea there are 23 long samples (each about 10 minutes) with name like"Recording_001.***".

How do you divide the long sample into short samples( only 24 samples if not divide. it is a so small examples size)?

Thanks in advance

**Comment by Svito-zar** [comment]
Thank you for your question, @chuangyu-robotics. 

Every training sample is 3s (60 frames) long and the training dataset is split into 3s long segment by going through each training sequence by sliding window, resulting in several hundred thousands training speech-gesture sequence pairs.

The code we provided for the [GENEA Challenge](https://genea-workshop.github.io/2020/) is located in the separate brunch: https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/tree/GENEA_2020

You can see the code for it in the `process_dataset.py` script at this brunch on line 112 :
https://github.com/GestureGeneration/Speech_driven_gesture_generation_with_autoencoder/blob/GENEA_2020/data_processing/process_dataset.py#L112

Did I answer your question?

**Comment by chuangyu-robotics** [comment]
clear and inpoint~ great! many thanks~ have a good day~
